// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.5
// source: inter.proto

package inter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepId   int32  `protobuf:"varint,3,opt,name=depId,proto3" json:"depId,omitempty"`
	OrgId   int32  `protobuf:"varint,4,opt,name=orgId,proto3" json:"orgId,omitempty"`
	DepName string `protobuf:"bytes,5,opt,name=depName,proto3" json:"depName,omitempty"`
	OrgName string `protobuf:"bytes,6,opt,name=orgName,proto3" json:"orgName,omitempty"`
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_inter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_inter_proto_rawDescGZIP(), []int{0}
}

func (x *AddReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddReq) GetDepId() int32 {
	if x != nil {
		return x.DepId
	}
	return 0
}

func (x *AddReq) GetOrgId() int32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *AddReq) GetDepName() string {
	if x != nil {
		return x.DepName
	}
	return ""
}

func (x *AddReq) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

type InterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Depid int64 `protobuf:"varint,2,opt,name=depid,proto3" json:"depid,omitempty"`
}

func (x *InterReq) Reset() {
	*x = InterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterReq) ProtoMessage() {}

func (x *InterReq) ProtoReflect() protoreflect.Message {
	mi := &file_inter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterReq.ProtoReflect.Descriptor instead.
func (*InterReq) Descriptor() ([]byte, []int) {
	return file_inter_proto_rawDescGZIP(), []int{1}
}

func (x *InterReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *InterReq) GetDepid() int64 {
	if x != nil {
		return x.Depid
	}
	return 0
}

type IntersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DepId int32 `protobuf:"varint,1,opt,name=depId,proto3" json:"depId,omitempty"`
}

func (x *IntersReq) Reset() {
	*x = IntersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntersReq) ProtoMessage() {}

func (x *IntersReq) ProtoReflect() protoreflect.Message {
	mi := &file_inter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntersReq.ProtoReflect.Descriptor instead.
func (*IntersReq) Descriptor() ([]byte, []int) {
	return file_inter_proto_rawDescGZIP(), []int{2}
}

func (x *IntersReq) GetDepId() int32 {
	if x != nil {
		return x.DepId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_inter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_inter_proto_rawDescGZIP(), []int{3}
}

type IntersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*InterInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *IntersResp) Reset() {
	*x = IntersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntersResp) ProtoMessage() {}

func (x *IntersResp) ProtoReflect() protoreflect.Message {
	mi := &file_inter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntersResp.ProtoReflect.Descriptor instead.
func (*IntersResp) Descriptor() ([]byte, []int) {
	return file_inter_proto_rawDescGZIP(), []int{4}
}

func (x *IntersResp) GetInfos() []*InterInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type InterInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid  int64  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *InterInfo) Reset() {
	*x = InterInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterInfo) ProtoMessage() {}

func (x *InterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterInfo.ProtoReflect.Descriptor instead.
func (*InterInfo) Descriptor() ([]byte, []int) {
	return file_inter_proto_rawDescGZIP(), []int{5}
}

func (x *InterInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InterInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *InterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateInterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   int32  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepId int32  `protobuf:"varint,3,opt,name=depId,proto3" json:"depId,omitempty"`
}

func (x *UpdateInterReq) Reset() {
	*x = UpdateInterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInterReq) ProtoMessage() {}

func (x *UpdateInterReq) ProtoReflect() protoreflect.Message {
	mi := &file_inter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInterReq.ProtoReflect.Descriptor instead.
func (*UpdateInterReq) Descriptor() ([]byte, []int) {
	return file_inter_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateInterReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateInterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateInterReq) GetDepId() int32 {
	if x != nil {
		return x.DepId
	}
	return 0
}

var File_inter_proto protoreflect.FileDescriptor

var file_inter_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x22, 0x8e, 0x01, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x72, 0x67, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f,
	0x72, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x64, 0x65, 0x70, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x09, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65, 0x70, 0x49, 0x64, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x34, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x41, 0x0a, 0x09, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4c,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65, 0x70, 0x49, 0x64, 0x32, 0xca, 0x01, 0x0a,
	0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x08,
	0x61, 0x64, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x0d, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x30, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x10, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x11, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inter_proto_rawDescOnce sync.Once
	file_inter_proto_rawDescData = file_inter_proto_rawDesc
)

func file_inter_proto_rawDescGZIP() []byte {
	file_inter_proto_rawDescOnce.Do(func() {
		file_inter_proto_rawDescData = protoimpl.X.CompressGZIP(file_inter_proto_rawDescData)
	})
	return file_inter_proto_rawDescData
}

var file_inter_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_inter_proto_goTypes = []interface{}{
	(*AddReq)(nil),         // 0: inter.AddReq
	(*InterReq)(nil),       // 1: inter.InterReq
	(*IntersReq)(nil),      // 2: inter.IntersReq
	(*Empty)(nil),          // 3: inter.Empty
	(*IntersResp)(nil),     // 4: inter.IntersResp
	(*InterInfo)(nil),      // 5: inter.InterInfo
	(*UpdateInterReq)(nil), // 6: inter.UpdateInterReq
}
var file_inter_proto_depIdxs = []int32{
	5, // 0: inter.IntersResp.infos:type_name -> inter.InterInfo
	0, // 1: inter.Interviewer.addInter:input_type -> inter.AddReq
	1, // 2: inter.Interviewer.DeleteInter:input_type -> inter.InterReq
	2, // 3: inter.Interviewer.GetInters:input_type -> inter.IntersReq
	6, // 4: inter.Interviewer.UpdateInter:input_type -> inter.UpdateInterReq
	3, // 5: inter.Interviewer.addInter:output_type -> inter.Empty
	3, // 6: inter.Interviewer.DeleteInter:output_type -> inter.Empty
	4, // 7: inter.Interviewer.GetInters:output_type -> inter.IntersResp
	3, // 8: inter.Interviewer.UpdateInter:output_type -> inter.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inter_proto_init() }
func file_inter_proto_init() {
	if File_inter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateInterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inter_proto_goTypes,
		DependencyIndexes: file_inter_proto_depIdxs,
		MessageInfos:      file_inter_proto_msgTypes,
	}.Build()
	File_inter_proto = out.File
	file_inter_proto_rawDesc = nil
	file_inter_proto_goTypes = nil
	file_inter_proto_depIdxs = nil
}
