// Code generated by goctl. DO NOT EDIT.
package types

type GetOrgDataRsp struct {
	Org Data   `json:"org"`
	Dep []Data `json:"dep"`
}

type Data struct {
	ID     int    `json:"Id"`
	Name   string `json:"name"`   // 名称
	Sum    int    `json:"sum"`    // 总数
	Pass   int    `json:"pass"`   // 通过人数
	Male   int    `json:"male"`   // 通过的男生数量
	Female int    `json:"female"` // 通过的女生数量
}

type LoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type RegReq struct {
	Name     string `json:"name"`
	Account  string `json:"account"`
	Password string `json:"password"`
}

type DepRsp struct {
	Name     string `json:"name,omitempty"`
	Account  string `json:"account,omitempty"`
	Password string `json:"password,omitempty"`
	ID       int    `json:"id,omitempty"`
}

type DepsRsp struct {
	Departments []DepRsp `json:"departments"`
}

type CommonReply struct {
	Id           int64  `json:"id,omitempty"`
	Name         string `json:"name,omitempty"`
	AccessToken  string `json:"accessToken,omitempty"`
	AccessExpire int64  `json:"accessExpire,omitempty"`
	RefreshAfter int64  `json:"refreshAfter,omitempty"`
}

type IdReq struct {
	Id string `path:"id"`
}

type UdpReq struct {
	Id       string `path:"id"`
	Name     string `json:"name,optional"`
	Account  string `json:"account,optional"`
	Password string `json:"password,optional"`
}

type ATimeReq struct {
	Start int64 `json:"start"`
	End   int64 `json:"end"`
}

type MsgRsp struct {
	Msg string `json:"msg"`
}

type TimeResp struct {
	Start int64 `json:"start"`
	End   int64 `json:"end"`
}
