// Code generated by goctl. DO NOT EDIT.
package types

type AddInterReq struct {
	Uid  int    `json:"uid"`
	Name string `json:"name"`
}

type AddInterRsp struct {
	Msg string `json:"msg"`
}

type UpdateInterReq struct {
	Uid  int    `json:"uid"`
	Name string `json:"name"`
}

type UpdateInterRsp struct {
	Msg string `json:"msg"`
}

type AInterReq struct {
	Uid []int `json:"uid"`
	Num int   `path:"num"`
}

type AinterRsp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type EnrollReq struct {
	Uid []int `json:"uid"`
}

type UsersInfo struct {
	Sum   int        `json:"sum"`
	Users []UserInfo `json:"users"`
}

type UserInfo struct {
	Uid        int    `json:"uid"`
	Name       string `json:"name"`
	Sex        string `json:"sex"`
	Major      string `json:"major"`
	AddressNum string `json:"address_num"`
	Phone      string `json:"phone"`
	Email      string `json:"email"`
	StudentNum string `json:"student_num"`
	Intro      string `json:"intro"`
	Status     int    `json:"status"`
	Eva        string `json:"eva"`
	Mark       int    `json:"mark"`
}

type UsersInfo2 struct {
	Sum   int         `json:"sum"`
	Users []UserInfo2 `json:"users"`
}

type UserInfo2 struct {
	Uid          int    `json:"uid"`
	Name         string `json:"name"`
	Sex          string `json:"sex"`
	Phone        string `json:"phone"`
	Email        string `json:"email"`
	StudentNum   string `json:"student_num"`
	Intro        string `json:"intro"`
	SecondStatus int    `json:"second_status"`
	Eva          string `json:"eva"`
	Mark         int    `json:"mark"`
}

type Msg struct {
	Msg string `json:"msg"`
}

type UidInfo struct {
	Num int   `path:"num"`
	UID []int `json:"uid"`
}

type DataRsp struct {
	RegSum     int `json:"reg_sum"`
	RegMale    int `json:"reg_male"`
	RegFemale  int `json:"reg_female"`
	PassSum    int `json:"pass_sum"`
	PassMale   int `json:"pass_male"`
	PassFemale int `json:"pass_female"`
}

type LoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type CommonReply struct {
	Id           int    `json:"id,omitempty"`
	Name         string `json:"name,omitempty"`
	OrgId        int    `json:"org_id,omitempty"`
	OrgName      string `json:"org_name,omitempty"`
	AccessToken  string `json:"accessToken,omitempty"`
	AccessExpire int64  `json:"accessExpire,omitempty"`
	RefreshAfter int64  `json:"refreshAfter,omitempty"`
}

type InterReq struct {
	Uid   int `path:"uid"`
	DepId int `json:"depId,omitempty"`
}

type InterdelReq struct {
	Uid int `path:"uid"`
}

type InterInfosResp struct {
	Infos []InterInfo `json:"infos"`
}

type InterInfo struct {
	Id   int64  `json:"id"`
	Uid  int64  `json:"uid"`
	Name string `json:"name"`
}

type SetInterConfReq struct {
	Turn         int    `path:"turn"`
	Start        int64  `json:"start"`
	End          int64  `json:"end"`
	InterAddress string `json:"inter_address"`
	ContactPhone string `json:"contact_phone"`
}

type GetInterConfReq struct {
	Turn int `path:"turn"`
}

type GetInterConfResp struct {
	DepId        int64  `json:"dep_id"`
	Turn         int    `json:"turn"`
	Start        int64  `json:"start"`
	End          int64  `json:"end"`
	InterAddress string `json:"inter_address"`
	ContactPhone string `json:"contact_phone"`
}

type AddEnrollReq struct {
	Uid        int64  `json:"uid"`
	Name       string `json:"name" binding:"required"`
	Sex        string `json:"sex,options=男|女"`
	StudentNum string `json:"student_num" binding:"required"`
	AddressNum string `json:"address_num,optional"`
	Major      string `json:"major,optional"`
	PhoneNum   string `json:"phone_num" binding:"required"`
	Email      string `json:"email" binding:"required"`
	Intro      string `json:"intro" binding:"required"`
}

type DeleteEnrolledReq struct {
	Uids []int `json:"uids"`
}

type SendInterNoticeReq struct {
	Num  int   `path:"num"`
	Uids []int `json:"uids"`
}

type OutReq struct {
	Num int   `path:"num"`
	Uid []int `json:"uid"`
}
