// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"uapply-micro/service/user/cmd/rpc/internal/logic"
	"uapply-micro/service/user/cmd/rpc/internal/svc"
	"uapply-micro/service/user/cmd/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 获取用户性别
func (s *UserServer) GetUserSex(ctx context.Context, in *user.GetSexReq) (*user.GetSexRsp, error) {
	l := logic.NewGetUserSexLogic(ctx, s.svcCtx)
	return l.GetUserSex(in)
}

// 获取用户信息
func (s *UserServer) GetUsers(ctx context.Context, in *user.GetSexReq) (*user.GetUsersRsp, error) {
	l := logic.NewGetUsersLogic(ctx, s.svcCtx)
	return l.GetUsers(in)
}

// 根据uid获取用户信息
func (s *UserServer) GetUserByUid(ctx context.Context, in *user.UserUid) (*user.UserInfo, error) {
	l := logic.NewGetUserByUidLogic(ctx, s.svcCtx)
	return l.GetUserByUid(in)
}

// 保存简历，该接口会做参数校验
func (s *UserServer) SaveResume(ctx context.Context, in *user.UserInfo) (*user.Empty, error) {
	l := logic.NewSaveResumeLogic(ctx, s.svcCtx)
	return l.SaveResume(in)
}
