// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	department "uapply-micro/service/department/cmd/api/internal/handler/department"
	"uapply-micro/service/department/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/dep/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/dep/reg-data",
				Handler: department.GetRegDataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/pass/:num",
				Handler: department.PassHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/enroll",
				Handler: department.EnrollHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/out/:num",
				Handler: department.OutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/getusers-first",
				Handler: department.GetUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/getusers-first/interviewed",
				Handler: department.GetUsersInterviewedHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/getout",
				Handler: department.GetOutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/getenroll",
				Handler: department.GetEnrollHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/a2i/:num",
				Handler: department.Announce2InterviewHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/add-inter",
				Handler: department.ADDInterviewerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dep/delete-Inter/:uid",
				Handler: department.DeleteInterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dep/inters",
				Handler: department.GetIntersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/updateInter",
				Handler: department.UpdateInterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/set-conf/:turn",
				Handler: department.SetInterConfHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dep/get-conf/:turn",
				Handler: department.GetInterConfHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/add-enroll",
				Handler: department.AddEnrollHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/dep/del-enrolled",
				Handler: department.DeleteEnrolledHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dep/send-inter-msg/:num",
				Handler: department.SendInterMsgHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
