// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "uapply-micro/service/user/cmd/api/internal/handler/user"
	"uapply-micro/service/user/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/org-enrolling",
				Handler: GetOrgEnrollingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/login/:code",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/mini-code",
				Handler: MiniCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login-xd",
				Handler: UserLoginXdHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/resume",
				Handler: user.AddResumeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/org-deps/:id",
				Handler: user.GetDepsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/register",
				Handler: user.GetRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/check-resume",
				Handler: user.CheckResumeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
