// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSexReq struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=Ids,proto3" json:"Ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSexReq) Reset()         { *m = GetSexReq{} }
func (m *GetSexReq) String() string { return proto.CompactTextString(m) }
func (*GetSexReq) ProtoMessage()    {}
func (*GetSexReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetSexReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSexReq.Unmarshal(m, b)
}
func (m *GetSexReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSexReq.Marshal(b, m, deterministic)
}
func (m *GetSexReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSexReq.Merge(m, src)
}
func (m *GetSexReq) XXX_Size() int {
	return xxx_messageInfo_GetSexReq.Size(m)
}
func (m *GetSexReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSexReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSexReq proto.InternalMessageInfo

func (m *GetSexReq) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetSexRsp struct {
	Sexs                 []string `protobuf:"bytes,1,rep,name=sexs,proto3" json:"sexs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSexRsp) Reset()         { *m = GetSexRsp{} }
func (m *GetSexRsp) String() string { return proto.CompactTextString(m) }
func (*GetSexRsp) ProtoMessage()    {}
func (*GetSexRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetSexRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSexRsp.Unmarshal(m, b)
}
func (m *GetSexRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSexRsp.Marshal(b, m, deterministic)
}
func (m *GetSexRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSexRsp.Merge(m, src)
}
func (m *GetSexRsp) XXX_Size() int {
	return xxx_messageInfo_GetSexRsp.Size(m)
}
func (m *GetSexRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSexRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSexRsp proto.InternalMessageInfo

func (m *GetSexRsp) GetSexs() []string {
	if m != nil {
		return m.Sexs
	}
	return nil
}

type GetUsersRsp struct {
	Users                []*UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetUsersRsp) Reset()         { *m = GetUsersRsp{} }
func (m *GetUsersRsp) String() string { return proto.CompactTextString(m) }
func (*GetUsersRsp) ProtoMessage()    {}
func (*GetUsersRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUsersRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRsp.Unmarshal(m, b)
}
func (m *GetUsersRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRsp.Marshal(b, m, deterministic)
}
func (m *GetUsersRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRsp.Merge(m, src)
}
func (m *GetUsersRsp) XXX_Size() int {
	return xxx_messageInfo_GetUsersRsp.Size(m)
}
func (m *GetUsersRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRsp proto.InternalMessageInfo

func (m *GetUsersRsp) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserInfo struct {
	Uid                  int64    `protobuf:"varint,9,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Sex                  string   `protobuf:"bytes,2,opt,name=sex,proto3" json:"sex,omitempty"`
	StudentNum           string   `protobuf:"bytes,3,opt,name=StudentNum,proto3" json:"StudentNum,omitempty"`
	AddressNum           string   `protobuf:"bytes,4,opt,name=AddressNum,proto3" json:"AddressNum,omitempty"`
	Major                string   `protobuf:"bytes,5,opt,name=Major,proto3" json:"Major,omitempty"`
	PhoneNum             string   `protobuf:"bytes,6,opt,name=PhoneNum,proto3" json:"PhoneNum,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=Email,proto3" json:"Email,omitempty"`
	Intro                string   `protobuf:"bytes,8,opt,name=Intro,proto3" json:"Intro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *UserInfo) GetStudentNum() string {
	if m != nil {
		return m.StudentNum
	}
	return ""
}

func (m *UserInfo) GetAddressNum() string {
	if m != nil {
		return m.AddressNum
	}
	return ""
}

func (m *UserInfo) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *UserInfo) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

type UserUid struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUid) Reset()         { *m = UserUid{} }
func (m *UserUid) String() string { return proto.CompactTextString(m) }
func (*UserUid) ProtoMessage()    {}
func (*UserUid) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserUid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUid.Unmarshal(m, b)
}
func (m *UserUid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUid.Marshal(b, m, deterministic)
}
func (m *UserUid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUid.Merge(m, src)
}
func (m *UserUid) XXX_Size() int {
	return xxx_messageInfo_UserUid.Size(m)
}
func (m *UserUid) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUid.DiscardUnknown(m)
}

var xxx_messageInfo_UserUid proto.InternalMessageInfo

func (m *UserUid) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetSexReq)(nil), "user.GetSexReq")
	proto.RegisterType((*GetSexRsp)(nil), "user.GetSexRsp")
	proto.RegisterType((*GetUsersRsp)(nil), "user.GetUsersRsp")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*UserUid)(nil), "user.UserUid")
	proto.RegisterType((*Empty)(nil), "user.Empty")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x4d, 0x4e, 0xfb, 0x30,
	0x10, 0xc5, 0x95, 0x7f, 0xfa, 0x91, 0x4e, 0xff, 0x40, 0xb1, 0x58, 0x58, 0x41, 0x40, 0x15, 0xb1,
	0x80, 0x05, 0x59, 0xb4, 0x27, 0x00, 0x09, 0x55, 0x5d, 0x50, 0xa1, 0x44, 0x39, 0x40, 0x90, 0x07,
	0x11, 0x44, 0x3e, 0x88, 0x1d, 0x94, 0xde, 0x8e, 0xa3, 0x70, 0x14, 0x34, 0xe3, 0x36, 0x85, 0xb2,
	0x7b, 0xef, 0xfd, 0xc6, 0x9e, 0x8c, 0x27, 0x00, 0x8d, 0xc6, 0x3a, 0xac, 0xea, 0xd2, 0x94, 0xa2,
	0x47, 0x3a, 0x38, 0x83, 0xd1, 0x02, 0x4d, 0x8c, 0x6d, 0x84, 0xef, 0x62, 0x02, 0xee, 0x52, 0x69,
	0xe9, 0x4c, 0xdd, 0x2b, 0x37, 0x22, 0x19, 0x5c, 0x74, 0x58, 0x57, 0x42, 0x40, 0x4f, 0x63, 0x6b,
	0xf9, 0x28, 0x62, 0x1d, 0xcc, 0x61, 0xbc, 0x40, 0x93, 0x68, 0xac, 0x35, 0x95, 0x5c, 0x42, 0x9f,
	0xae, 0xb5, 0x35, 0xe3, 0xd9, 0x61, 0xc8, 0x0d, 0x09, 0x2f, 0x8b, 0xe7, 0x32, 0xb2, 0x30, 0xf8,
	0x72, 0xc0, 0xdb, 0x66, 0xd4, 0x34, 0xc9, 0x94, 0x1c, 0x4d, 0x1d, 0x6a, 0x9a, 0x64, 0x8a, 0xfa,
	0xac, 0xd2, 0x1c, 0xa5, 0x33, 0x75, 0xa8, 0x0f, 0x69, 0xaa, 0xd2, 0xd8, 0xca, 0x7f, 0x1c, 0x91,
	0x14, 0xe7, 0x00, 0xb1, 0x69, 0x14, 0x16, 0x66, 0xd5, 0xe4, 0xd2, 0x65, 0xf0, 0x23, 0x21, 0x7e,
	0xab, 0x54, 0x8d, 0x5a, 0x13, 0xef, 0x59, 0xbe, 0x4b, 0xc4, 0x09, 0xf4, 0x1f, 0xd2, 0xd7, 0xb2,
	0x96, 0x7d, 0x46, 0xd6, 0x08, 0x1f, 0xbc, 0xc7, 0x97, 0xb2, 0x40, 0x3a, 0x33, 0x60, 0xd0, 0x79,
	0x3a, 0x71, 0x9f, 0xa7, 0xd9, 0x9b, 0x1c, 0xda, 0x13, 0x6c, 0x28, 0x5d, 0x16, 0xa6, 0x2e, 0xa5,
	0x67, 0x53, 0x36, 0xc1, 0x29, 0x0c, 0x69, 0x42, 0x1a, 0x67, 0x02, 0x6e, 0x93, 0x29, 0x9e, 0xc6,
	0x8d, 0x48, 0x06, 0x43, 0xba, 0xa8, 0x32, 0xeb, 0xd9, 0xa7, 0x03, 0xbc, 0x06, 0x11, 0x02, 0x6c,
	0x9e, 0x31, 0xc6, 0x56, 0x1c, 0xd9, 0x67, 0xeb, 0x16, 0xe3, 0xff, 0x0e, 0x74, 0x25, 0x42, 0xf0,
	0xb6, 0xcf, 0xfe, 0xb7, 0xfa, 0xb8, 0x0b, 0xba, 0xbd, 0xdc, 0xc0, 0xff, 0x8d, 0xbd, 0x5b, 0xd3,
	0x37, 0x1d, 0xec, 0x16, 0x93, 0x64, 0xca, 0xdf, 0xdb, 0x93, 0xb8, 0x06, 0x88, 0xd3, 0x0f, 0x8c,
	0x50, 0x37, 0x39, 0x8a, 0x3d, 0xea, 0x8f, 0xad, 0xe7, 0x11, 0x9e, 0x06, 0xfc, 0x37, 0xcd, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x82, 0xa3, 0x02, 0x5b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	// 获取用户性别
	GetUserSex(ctx context.Context, in *GetSexReq, opts ...grpc.CallOption) (*GetSexRsp, error)
	// 获取用户信息
	GetUsers(ctx context.Context, in *GetSexReq, opts ...grpc.CallOption) (*GetUsersRsp, error)
	// 根据uid获取用户信息
	GetUserByUid(ctx context.Context, in *UserUid, opts ...grpc.CallOption) (*UserInfo, error)
	// 保存简历，该接口会做参数校验
	SaveResume(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*Empty, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserSex(ctx context.Context, in *GetSexReq, opts ...grpc.CallOption) (*GetSexRsp, error) {
	out := new(GetSexRsp)
	err := c.cc.Invoke(ctx, "/user.user/GetUserSex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUsers(ctx context.Context, in *GetSexReq, opts ...grpc.CallOption) (*GetUsersRsp, error) {
	out := new(GetUsersRsp)
	err := c.cc.Invoke(ctx, "/user.user/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserByUid(ctx context.Context, in *UserUid, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/user.user/GetUserByUid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SaveResume(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/user.user/SaveResume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	// 获取用户性别
	GetUserSex(context.Context, *GetSexReq) (*GetSexRsp, error)
	// 获取用户信息
	GetUsers(context.Context, *GetSexReq) (*GetUsersRsp, error)
	// 根据uid获取用户信息
	GetUserByUid(context.Context, *UserUid) (*UserInfo, error)
	// 保存简历，该接口会做参数校验
	SaveResume(context.Context, *UserInfo) (*Empty, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) GetUserSex(ctx context.Context, req *GetSexReq) (*GetSexRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSex not implemented")
}
func (*UnimplementedUserServer) GetUsers(ctx context.Context, req *GetSexReq) (*GetUsersRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedUserServer) GetUserByUid(ctx context.Context, req *UserUid) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByUid not implemented")
}
func (*UnimplementedUserServer) SaveResume(ctx context.Context, req *UserInfo) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveResume not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUserSex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserSex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetUserSex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserSex(ctx, req.(*GetSexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUsers(ctx, req.(*GetSexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserByUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserByUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetUserByUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserByUid(ctx, req.(*UserUid))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SaveResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SaveResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/SaveResume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SaveResume(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.user",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserSex",
			Handler:    _User_GetUserSex_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _User_GetUsers_Handler,
		},
		{
			MethodName: "GetUserByUid",
			Handler:    _User_GetUserByUid_Handler,
		},
		{
			MethodName: "SaveResume",
			Handler:    _User_SaveResume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
