// Code generated by goctl. DO NOT EDIT!
// Source: organization.proto

package server

import (
	"context"

	"uapply-micro/service/organization/cmd/rpc/internal/logic"
	"uapply-micro/service/organization/cmd/rpc/internal/svc"
	"uapply-micro/service/organization/cmd/rpc/organization"
)

type OrganizationServer struct {
	svcCtx *svc.ServiceContext
}

func NewOrganizationServer(svcCtx *svc.ServiceContext) *OrganizationServer {
	return &OrganizationServer{
		svcCtx: svcCtx,
	}
}

func (s *OrganizationServer) GetAllOrgTime(ctx context.Context, in *organization.Empty) (*organization.TimeRsp, error) {
	l := logic.NewGetAllOrgTimeLogic(ctx, s.svcCtx)
	return l.GetAllOrgTime(in)
}
