// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Code string `path:"code"`
}

type LoginRsp struct {
	AccessToken  string `json:"accessToken,omitempty"`
	AccessExpire int64  `json:"accessExpire,omitempty"`
	RefreshAfter int64  `json:"refreshAfter,omitempty"`
	UID          int    `json:"uid"`
}

type GetReq struct {
	Num   int `path:"num"`
	DepId int `json:"depId"`
	UID   int `json:"uid"`
}

type CommonRsq struct {
	Name       string `json:"name"`
	Sex        string `json:"sex""`
	StudentNum string `json:"student_num"`
	AddressNum string `json:"address_num"`
	Major      string `json:"major"`
	PhoneNum   string `json:"phone_num"`
	Email      string `json:"email"`
	Intro      string `json:"intro"`
	Tag        int    `json:"tag"`
}

type MarkReq struct {
	DepId int    `json:"depId"`
	Num   int    `path:"num"`
	UID   int    `json:"uid"`
	Eva   string `json:"eva"`
	Mark  int    `json:"mark"`
}

type EvaRsq struct {
	Eva  string `json:"eva"`
	Mark int    `json:"mark"`
}

type InterDepOrg struct {
	Dep map[int]string `json:"depId"`
	Org map[int]string `json:"orgId"`
}

type MsgRsq struct {
	Msg string `json:"msg"`
}

type TurnReq struct {
	Uid   int `json:"uid"`
	DepId int `json:"depId"`
}

type TurnResp struct {
	Turn int `json:"turn"`
}

type DepDataReq struct {
	DepId int `path:"depId"`
}

type DepDataResp struct {
	DepId      int `json:"depId"`
	Sum        int `json:"sum"`
	SumMale    int `json:"sum_male"`
	SumFemale  int `json:"sum_female"`
	Pass       int `json:"pass"`
	PassMale   int `json:"pass_male"`
	PassFemale int `json:"pass_female"`
}
